packages:
  - packages/*
  - apps/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

link-workspace-packages: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - unrs-resolver
