name: dockerize
description: 'Build, Push Docker Container'
inputs:
  project_id:
    description: 'Google Cloud Project ID'
    required: true
  service_name:
    description: 'Google Cloud Run Service Name'
    required: true
  credentials_json:
    description: 'Google Cloud Service Account JSON'
    required: true
  gcr_hostname:
    description: 'Google Cloud Run Docker Repository'
    required: false
    default: gcr.io
  dockerfile:
    description: 'Location of Dockerfile'
    required: true
    default: ./Dockerfile
  artifact_registry:
    description: 'Artifact Registry'
    required: false
    default: us-docker.pkg.dev

runs:
  using: 'composite'
  steps:
    - id: 'auth'
      name: gcloud auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ inputs.credentials_json }}'

    - name: gcloud sdk
      uses: google-github-actions/setup-gcloud@v2
      with:
        skip_install: true

    - name: gcloud configure docker
      run: gcloud auth configure-docker ${{ inputs.artifact_registry }}
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # guide to docker caching: https://blacksmith.sh/blog/cache-is-king-a-guide-for-docker-layer-caching-in-github-actions
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ inputs.gcr_hostname }}/${{ inputs.project_id }}/${{ inputs.service_name }}:${{ github.sha }}
        cache-from: type=registry,ref=${{ inputs.gcr_hostname }}/${{ inputs.project_id }}/${{ inputs.service_name }}/cache:latest
        cache-to: type=inline,mode=min
